version: '3'

services:
  web:
    build:
      context: ./docker/django
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/app
    ports:
      - "8000:8000"
